@startuml

title Cenário da Aplicação Citações
left to right direction

' Atores
'
actor :Usuário:              as u1
actor :Repositório\nRemoto:  as u2

' Casos de Uso
'
rectangle Citações {
  usecase (Requisita uma citação)        as uc1
  usecase (Formata a citação)            as uc2
  usecase (Acessa o repositório local)   as uc3
  usecase (Personaliza a visualização)   as uc4
  usecase (Sincroniza o repositório)     as uc5
  usecase (Persiste a atualização)       as uc6
  usecase (Notifica sobre atualizações)  as uc7
}

' Interação
'
u1 --> uc1
uc1 ..> uc2 : include
uc1 ..> uc3 : include

@enduml
